### ISSUE TITLE
Errores en el reporte de estudiante 

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-mod_kuet#35]
Buenas,

Como estudiante, al ir a ver el reporte de una sesión, vemos que aparecen diferentes problemas:

1. Como podéis ver en 1, Success: 0, cuando de correct hay 3. Esto parece que esta contando mal.
2. El texto Success marcado en 2, y el texto Correct marcado con el 3. ¿Porqué ponéis la cadena de texto diferente? Hablando con @JuanjoRossello no vemos el motivo.
3. ¿Que significa el 3 marcado con el número 4?

Un saludo
![Selecció_1018](https://github.com/UNIMOODLE/moodle-mod_jqshow---P2/assets/970116/31cb4bd8-36c1-499e-9a6f-a22788abb115)

**Comment by elena3ip** [comment]
@tmas0  podemos cerrar esta issue?
