### ISSUE TITLE
Vulnerabilidad crítica en servidor WebSocket de Moodle: Impacto en disponibilidad e integridad

### ISSUE THREAD

**Issue by RicardoUIB** [UNIMOODLE/moodle-mod_kuet#37]
El problema radica en la incapacidad del servidor para interpretar las tramas de control según lo especificado en el estándar The **WebSocket Protocol (RFC6455)**. 

Cuando se envían mensajes como **CLOSE** o **PING** al servidor _“unimoodleservercli.php “_ a través de WebSocket, en lugar de ser manejados correctamente, estos mensajes provocan la caída del servidor, lo que interrumpe el servicio y requiere un reinicio manual para restaurar la funcionalidad. Lo mismo sucede cuando el servidor recibe cualquier otro mensaje que no es capaz de interpretar. 

Además, es importante destacar que la vulnerabilidad asociada con este fallo es significativa desde una perspectiva de seguridad. 

Dado que el puerto **WebSocket** está expuesto públicamente a internet, cualquier individuo malintencionado podría explotar esta vulnerabilidad enviando solicitudes maliciosas al servidor. 

En las pruebas realizadas se ha utilizado la herramienta **Curl** para reproducir el bug así como el cliente Web Firefox programando un PING configurándolo con el parámetro **_“network.websocket.timeout.ping.request”_** en _“about:config”_. 

Esto resulta en una interrupción del servicio, lo que tiene un impacto negativo en la disponibilidad y la integridad de la plataforma Moodle.

**Comment by xpazv** [comment]
En revisión

**Comment by xpazv** [comment]
@juacas ¿Nos puedes indicar los pasos realizados usando CURL para generar el error, por favor?

¿Ocurre tambiñen con todos los otros navegadores del mercado (Chrome, Edge) o solo con el navegador Firefox? ¿Nos puedes indicar qué versión de Firefox se ha usado?

**Comment by juacas** [comment]
Os darán feedback los encargados del P2.
Pero quiero aclarar algo de tu pregunta.

No es un problema de un navegador en cuestión, el problema es que el servidor websocket es vulnerable a ciertos mensajes (casi cualquier cosa que no se espere) y se crashea.

Eso hace trivial montar un ataque DoS a Kuet.

**Comment by xpazv** [comment]
Lo entendemos @juacas Buscábamos más herramientas para poder reproducir de la incidencia de la mayor cantidad de maneras posible.

Quedamos a la espera de los detalles técnicos para poder reproducir la incidencia y avanzar en posibles soluciones.

**Comment by RicardoUIB** [comment]
Las pruebas se realizaron con:
- Windows 10 Pro versión 22H2 - Firefox 102.5.0esr
- Ubuntu 22.04.4 LTS Firefox 124.0 (64-bit)
- Windows 10 Pro versión 22H2 - Chrome 123.0.6312.58 (Compilación oficial)(64bits)
- Windows 10 Pro versión 22H2 - Chrome 123.0.6312.59 (Compilación oficial)(64bits)

En Firefox se utilizó el parámetro "network.websocket.timeout.ping.request" configurado con un valor de 5 segundos para enviar un PING al servidor (RFC6455).
En Chrome y Firefox se utilizó la extensión "Simple WebSocket Client" para enviar cualquier tipo de mensaje contemplado en el RFC6455.

El siguiente comando con Curl se utilizó para establecer una conexión con el servidor de WebSocket. Se configuró para que se cerrara automáticamente a los 5 segundos:
>curl  -m 5 https://host:port

**Comment by xpazv** [comment]
Reproducido error con la extensión de Chrome indicada.

**Comment by xpazv** [comment]
Se ha subido corrección que solventa el problema de caída por recibir tramas de datos que el servidor no entiende.

@juacas Por favor, validad por vuestra parte el cambio realizado.

**Comment by RicardoUIB** [comment]
Probado y corregido. No hemos podido volver a reproducir.
Gtracias!
