### ISSUE TITLE
Problemas para despliegue en Modle Plugins

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_kuet#38]
No se puede desplegar en Moodle Plugins por las siguientes carencias:

Code validation errors
Important File kuet/index.php must exist in archive and is not found.
Code validation warnings
Warning Maturity information ($plugin->maturity) not found in version.php
Warning Release name ($plugin->release) not found in version.php

index.php es un script importante que tiene que mostrar la lista de instancias de un curso.
Las otras dos son menos importantes. Deben ser:
maturity = MATURITY_RC
release = v0.0.1

**Comment by xpazv** [comment]
En revision.

**Comment by juacas** [comment]
¿Alguna novedad? Este ticket tenía que haberse resuelto hace varias semanas.

**Comment by elena3ip** [comment]
Disculpa @juacas  esto se subió en este [commit ](https://github.com/UNIMOODLE/moodle-mod_kuet/compare/33ea607aa338556d50dd20ae6696dbcb42b4a761...4211a035745c505342bfdbee9d1e0b47053a7d06)  el 1 de Abril.

**Comment by juacas** [comment]
OK, no había ninguna referencia a este ticket, solo se referenciaba al 38.
Lo anoto como cerrado.
