### ISSUE TITLE
12882 errors in Code prechecks in Moodle plugin directory

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_kuet#39]
Prechecks give a lot of issues (mainly in css):

Prechecker results: error
(12832 errors/733 warnings) => phplint (0/0), phpcs (653/268), js (0/140), css (12079/228), phpdoc (99/0), savepoint (0/0), thirdparty (0/0), grunt (1/1), shifter (0/0), mustache (0/96), gherkin (0/0),
PHP lint problems
(0 errors, 0 warnings)

**Comment by xpazv** [comment]
¿Es posible saber qué herramienta o herramientas se han usado para realizar dicha validación de código?

¿Es producto de la subida al repositorio de Moodle https://github.com/UNIMOODLE/moodle-mod_kuet/issues/39?

**Comment by juacas** [comment]
Efectivamente, es el precheck que realiza Moodle al subirlo al repositorio de plugins.

**Comment by xpazv** [comment]
Estamos trabajando en ello.

**Comment by xpazv** [comment]
Subidos cambios para los prechecks.

Indicar que se menciona la posibilidad de retirar los _important_ de algunos CSS, lo cual no es viable, pues tiene un impacto enorme de refactorización de código del front.

**Comment by juacas** [comment]
Plugin publicado!
Enhorabuena a todos.
