### ISSUE TITLE
Session configuration page 2 throws an error "($category) must be of type string"

### ISSUE THREAD

**Issue by Buda9** [UNIMOODLE/moodle-mod_kuet#47]
Moodle 4.4.1+

Hi there. Thank you for this great plugin. I have one issue to report, but I don't have time to debug it. On this page (link below) when I click next button for page 2, it throws an internal error. You can see error message below, too.

![Screenshot_149](https://github.com/UNIMOODLE/moodle-mod_kuet/assets/1422662/f071d8ed-45be-457f-9384-731d11f1d786)

Error message is this:

```
2024/06/28 13:51:37 [error] 2618152#2618152: *1547876 FastCGI sent in stderr: "PHP message: Default exception handler: Exception - mod_kuet\models\sessions::get_questions_for_category(): Argument #1 ($category) must be of type string, array given, called in [dirroot]/mod/kuet/classes/models/sessions.php on line 329 Debug:
Error code: generalexceptionmessage
* line 352 of /mod/kuet/classes/models/sessions.php: TypeError thrown
* line 329 of /mod/kuet/classes/models/sessions.php: call to mod_kuet\models\sessions->get_questions_for_category()
* line 863 of /mod/kuet/classes/models/sessions.php: call to mod_kuet\models\sessions->export_session_questions()
* line 81 of /mod/kuet/classes/output/views/sessions_view.php: call to mod_kuet\models\sessions->export()
* line 131 of /mod/kuet/classes/output/renderer.php: call to mod_kuet\output\views\sessions_view->export_for_template()
* line 503 of /lib/outputrenderers.php: call to mod_kuet\output\renderer->render_sessions_view()
* line 63 of /mod/kuet/sessions.php: call to plugin_renderer_base->render()
```

**Comment by LuksAO** [comment]
Hi. I replicated the bug on a Moodle 4.4.1 clean installation.

But once you enter at least one time on the course's question bank the error seems to disappear for me. Can you confirm this is the same behavior for you?

This is caused (I think) cause Moodle creates default top categories for contexts on the fly, so Kuet get a response from Moodle core API as if there were no category if no one has ever entered the question bank.

**Comment by Buda9** [comment]
@LuksAO Sorry for late reply. Indeed, that solved the issue. I was previously testing on demo site so I didn't have any questions in question bank. Thank you for your reply
